from collections.abc import Callable
from typing import Any

def IsWindowVisible(hwnd: int) -> bool: ...
def GetWindowText(hwnd: int) -> str: ...
def EnumWindows(callback: Callable[[int, Any], Any], extra: Any) -> None: ...
def GetWindowRect(hwnd: int) -> tuple[int, int, int, int]: ...
